# Generated by Django 4.2.27 on 2026-09-02 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Billet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=60, verbose_name="numéro")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("sayan", "Saiyan"),
                            ("super_sayan", "Super Saiyan"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="visiteur",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
