# Generated by Django 4.2.27 on 2026-09-02 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("park_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nom")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="attractions/", verbose_name="photo"
                    ),
                ),
                (
                    "max_people",
                    models.PositiveIntegerField(verbose_name="capacité maximale"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="billet",
            options={"ordering": ["-assigned_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="billet",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="assigné le"
            ),
        ),
        migrations.AlterField(
            model_name="billet",
            name="numero",
            field=models.CharField(max_length=60, unique=True, verbose_name="numéro"),
        ),
        migrations.AlterField(
            model_name="billet",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="visiteur",
            ),
        ),
    ]
