# Generated by Django 4.2.27 on 2026-09-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "park_management",
            "0002_attraction_alter_billet_options_billet_assigned_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AttractionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_people",
                    models.PositiveIntegerField(
                        default=0, verbose_name="capacité réelle"
                    ),
                ),
                ("min_duration", models.DurationField(verbose_name="durée minimale")),
                ("max_duration", models.DurationField(verbose_name="durée maximale")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "attraction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="park_management.attraction",
                        verbose_name="attraction",
                    ),
                ),
            ],
            options={
                "verbose_name": "état d'attraction",
                "verbose_name_plural": "états d'attraction",
                "ordering": ["attraction__name"],
            },
        ),
    ]
