# Generated by Django 4.2.27 on 2026-09-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("park_management", "0003_attractionstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="max_ready_waiting",
            field=models.PositiveIntegerField(
                default=0, verbose_name="maximum de billets prêts"
            ),
        ),
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="inscrit le"),
                ),
                ("is_ready", models.BooleanField(default=False, verbose_name="prêt")),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="prêt depuis"
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="park_management.attraction",
                        verbose_name="attraction",
                    ),
                ),
                (
                    "billet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="park_management.billet",
                        verbose_name="billet",
                    ),
                ),
            ],
            options={
                "verbose_name": "place dans la file",
                "verbose_name_plural": "places dans les files",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="AttractionVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="entré le"),
                ),
                (
                    "exited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="sorti le"
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="park_management.attraction",
                        verbose_name="attraction",
                    ),
                ),
                (
                    "billet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="park_management.billet",
                        verbose_name="billet",
                    ),
                ),
            ],
            options={
                "verbose_name": "présence dans l'attraction",
                "verbose_name_plural": "présences dans les attractions",
                "ordering": ["-entered_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="queueentry",
            constraint=models.UniqueConstraint(
                fields=("attraction", "billet"),
                name="un_billet_une_place_par_attraction",
            ),
        ),
        migrations.AddIndex(
            model_name="attractionvisit",
            index=models.Index(
                fields=["attraction", "exited_at"], name="visite_attraction_en_cours"
            ),
        ),
    ]
