# Generated by Django 4.2.27 on 2026-09-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_management", "0004_attraction_max_ready_waiting_queueentry_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attractionvisit",
            name="visite_attraction_en_cours",
        ),
        migrations.RemoveField(
            model_name="attractionvisit",
            name="exited_at",
        ),
        migrations.AlterField(
            model_name="attraction",
            name="max_ready_waiting",
            field=models.PositiveIntegerField(
                default=300, verbose_name="tolérance de l'état prêt (secondes)"
            ),
        ),
        migrations.AddConstraint(
            model_name="attractionvisit",
            constraint=models.UniqueConstraint(
                fields=("attraction", "billet"),
                name="un_billet_une_presence_par_attraction",
            ),
        ),
    ]
