# Generated by Django 4.2.27 on 2026-09-02 14:50

import datetime
from django.db import migrations, models


def copy_durations_from_state(apps, schema_editor):
    """
    Reprend sur chaque attraction les durées que portait son état, avant que le
    modèle ne disparaisse : les valeurs déjà saisies valent mieux que les
    valeurs par défaut des nouveaux champs.
    """
    AttractionState = apps.get_model("park_management", "AttractionState")
    for state in AttractionState.objects.all():
        AttractionState._meta.apps.get_model("park_management", "Attraction").objects.filter(
            pk=state.attraction_id
        ).update(min_duration=state.min_duration, max_duration=state.max_duration)


def noop(apps, schema_editor):
    """Rien à défaire : le retour en arrière recrée un état vide, sans durées à rendre."""


class Migration(migrations.Migration):

    dependencies = [
        (
            "park_management",
            "0005_remove_attractionvisit_visite_attraction_en_cours_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="max_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=300), verbose_name="durée maximale"
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="min_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120), verbose_name="durée minimale"
            ),
        ),
        migrations.RunPython(copy_durations_from_state, noop),
        migrations.DeleteModel(
            name="AttractionState",
        ),
    ]
